export const dom = {
  statusEl: document.getElementById("status"),
  eventTitleEl: document.getElementById("eventTitle"),
  eventSubEl: document.getElementById("eventSub"),
  eventSlugEl: document.getElementById("eventSlug"),
  liveResultLinkEl: document.getElementById("liveResultLink"),
  btcEl: document.getElementById("btcPrice"),
  priceToBeatEl: document.getElementById("priceToBeat"),
  canonicalPriceEl: document.getElementById("canonicalPrice"),
  fallbackPriceEl: document.getElementById("fallbackPrice"),
  deltaEl: document.getElementById("priceDelta"),
  minsEl: document.getElementById("timerMins"),
  secsEl: document.getElementById("timerSecs"),
  buyUpBtnEl: document.getElementById("buyUpBtn"),
  buyDownBtnEl: document.getElementById("buyDownBtn"),
  sellUpBtnEl: document.getElementById("sellUpBtn"),
  sellDownBtnEl: document.getElementById("sellDownBtn"),
  connectWalletBtnEl: document.getElementById("connectWalletBtn"),
  disconnectWalletBtnEl: document.getElementById("disconnectWalletBtn"),
  walletAddressEl: document.getElementById("walletAddress"),
  orderSizeEl: document.getElementById("orderSize"),
  logToggleEl: document.getElementById("logToggle"),
  downloadEventListBtnEl: document.getElementById("downloadEventListBtn"),
  downloadPriceFeedBtnEl: document.getElementById("downloadPriceFeedBtn"),
  targetTagEl: document.getElementById("targetTag"),
  chartEl: document.getElementById("priceChart")
};
