export const state = {
  currentSlug: null,
  conditionId: null,
  upTokenId: null,
  downTokenId: null,
  upOutcomeLabel: "Yes",
  downOutcomeLabel: "No",
  targetPriceCanonical: null,
  targetPriceFallback: null,
  targetPriceCanonicalTs: null,
  targetPriceCanonicalAnchorMs: null,
  latestPrice: null,
  upAsk: null,
  downAsk: null,
  upBid: null,
  downBid: null,
  currentWindowStartSec: null,
  currentWindowEndSec: null,
  ws: null,
  wsPingIntervalId: null,
  marketWs: null,
  marketWsPingIntervalId: null,
  marketWsReconnectTimeoutId: null,
  pricePoints: [],
  chartCtx: null,
  chartDpr: 1,
  eventCache: new Map(),
  orderSize: 1,
  marketSource: null,
  tradingBusy: false,
  bullpen: {
    serviceOnline: false,
    cliInstalled: false,
    loggedIn: false,
    address: null,
    addressMasked: "",
    approvalsOk: false,
    approvalsMessage: "",
    preflightOk: false,
    preflightMessage: "",
    sessionKeyLoaded: false,
    sessionKeyFingerprint: "",
    loginCommand: "bullpen login"
  }
};
