export const state = {
  currentSlug: null,
  conditionId: null,
  upTokenId: null,
  downTokenId: null,
  targetPriceCanonical: null,
  targetPriceFallback: null,
  targetPriceCanonicalTs: null,
  targetPriceCanonicalAnchorMs: null,
  latestPrice: null,
  upAsk: null,
  downAsk: null,
  currentWindowStartSec: null,
  currentWindowEndSec: null,
  ws: null,
  wsPingIntervalId: null,
  marketWs: null,
  marketWsPingIntervalId: null,
  marketWsReconnectTimeoutId: null,
  pricePoints: [],
  chartCtx: null,
  chartDpr: 1,
  eventCache: new Map()
};
